 /** Login  */
export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";

 /** LOGOUT  */
export const USER_LOGOUT="USER_LOGOUT";

 /** REGISTER  */
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL";
export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";


 /** NEW ARRIVALS  */
 export const USER_NEW_ARRIVALS_FAIL="USER_NEW_ARRIVALS_FAIL";
 export const USER_NEW_ARRIVALS_REQUEST="USER_NEW_ARRIVALS_REQUEST";
 export const USER_NEW_ARRIVALS_SUCCESS="USER_NEW_ARRIVALS_SUCCESS";
 


 /** UPDATE User  */
export const USER_UPDATE_FAIL="USER_UPDATE_FAIL";
export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS";


 /** UPDATE User Profile Picture */
 export const USER_UPDATE_Picture_FAIL="USER_UPDATE_Picture_FAIL";
 export const USER_UPDATE_Picture_REQUEST="USER_UPDATE_Picture_REQUEST";
 export const USER_UPDATE_Picture_SUCCESS="USER_UPDATE_Picture_SUCCESS";
 
 /** FORGOT PASSWORD */
export const USER_FORGOT_PASSWORD_REQUEST="USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_FAIL="USER_FORGOT_PASSWORD_FAIL";
export const USER_FORGOT_PASSWORD_SUCCESS="USER_FORGOT_PASSWORD_SUCCESS";

 /** REST PASSWORD */
export const USER_REST_PASSWORD_REQUEST="USER_REST_PASSWORD_REQUEST";
export const USER_REST_PASSWORD_FAIL="USER_REST_PASSWORD_FAIL";
export const USER_REST_PASSWORD_SUCCESS="USER_REST_PASSWORD_SUCCESS";


/**RETRIEVE TYPES */
export const RETRIEVE_TYPES_REQUEST = "RETRIEVE_TYPES_REQUEST";
export const RETRIEVE_TYPES_SUCCESS = "RETRIEVE_TYPES_SUCCESS";
export const RETRIEVE_TYPES_FAIL = "RETRIEVE_TYPES_FAIL";

/**RETRIEVE DEMAND */
export const RETRIEVE_DEMAND_REQUEST = "RETRIEVE_DEMAND_REQUEST";
export const RETRIEVE_DEMAND_SUCCESS = "RETRIEVE_DEMAND_SUCCESS";
export const RETRIEVE_DEMAND_FAIL = "RETRIEVE_DEMAND_FAIL";



/**RETRIEVE ATTRIBUTE */
export const RETRIEVE_ATTRIBUTE_REQUEST = "RETRIEVE_ATTRIBUTE_REQUEST";
export const RETRIEVE_ATTRIBUTE_SUCCESS = "RETRIEVE_ATTRIBUTE_SUCCESS";
export const RETRIEVE_ATTRIBUTE_FAIL = "RETRIEVE_ATTRIBUTE_FAIL";


/**DELETE USER */
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

/**DELETE ATTRIBUTE */
export const DELETE_ATTRIBUTE_REQUEST = "DELETE_ATTRIBUTE_REQUEST";
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS";
export const DELETE_ATTRIBUTE_FAIL = "DELETE_ATTRIBUTE_FAIL";



/**DELETE TYPE */
export const DELETE_TYPE_REQUEST = "DELETE_TYPE_REQUEST";
export const DELETE_TYPE_SUCCESS = "DELETE_TYPE_SUCCESS";
export const DELETE_TYPE_FAIL = "DELETE_TYPE_FAIL";

/**DELETE RULE */
export const DELETE_RULE_REQUEST = "DELETE_RULE_REQUEST";
export const DELETE_RULE_SUCCESS = "DELETE_URULE_SUCCESS";
export const DELETE_RULE_FAIL = "DELETE_RULE_FAIL";


/**RETRIEVE USER */
export const RETRIEVE_USER_REQUEST = "RETRIEVE_USER_REQUEST";
export const RETRIEVE_USER_SUCCESS = "RETRIEVE_USER_SUCCESS";
export const RETRIEVE_USER_FAIL = "RETRIEVE_USER_FAIL";


/**RETRIEVE ARTICLE */
export const RETRIEVE_ARTICLE_REQUEST = "RETRIEVE_ARTICLE_REQUEST";
export const RETRIEVE_ARTICLE_SUCCESS = "RETRIEVE_ARTICLE_SUCCESS";
export const RETRIEVE_ARTICLE_FAIL = "RETRIEVE_ARTICLE_FAIL";


/**RETRIEVE RANDOM ARTICLE */
export const RETRIEVE_RANDOM_ARTICLE_REQUEST = "RETRIEVE_RANDOM_ARTICLE_REQUEST";
export const RETRIEVE_RANDOM_ARTICLE_SUCCESS = "RETRIEVE_RANDOM_ARTICLE_SUCCESS";
export const RETRIEVE_RANDOM_ARTICLE_FAIL = "RETRIEVE_RANDOM_ARTICLE_FAIL";


/**RETRIEVE DEMAND AUTHOR */
export const RETRIEVE_DEMAND_AUTHOR_REQUEST = "RETRIEVE_DEMAND_AUTHOR_REQUEST";
export const RETRIEVE_DEMAND_AUTHOR_SUCCESS = "RETRIEVE_DEMAND_AUTHOR_SUCCESS";
export const RETRIEVE_DEMAND_AUTHOR_FAIL = "RETRIEVE_DEMAND_AUTHOR_FAIL";


/**RETRIEVE ARTICLE BY FILTER */
export const RETRIEVE_ARTICLE_BY_FILTER_REQUEST = "RETRIEVE_ARTICLE_BY_FILTER_REQUEST";
export const RETRIEVE_ARTICLE_BY_FILTER_SUCCESS = "RETRIEVE_ARTICLE_BY_FILTER_SUCCESS";
export const RETRIEVE_ARTICLE_BY_FILTER_FAIL = "RETRIEVE_ARTICLE_BY_FILTER_FAIL";

/**RETRIEVE USER BY FILTER */
export const RETRIEVE_USER_BY_FILTER_REQUEST = "RETRIEVE_USER_BY_FILTER_REQUEST";
export const RETRIEVE_USER_BY_FILTER_SUCCESS = "RETRIEVE_USER_BY_FILTER_SUCCESS";
export const RETRIEVE_USER_BY_FILTER_FAIL = "RETRIEVE_USER_BY_FILTER_FAIL";

/**RETRIEVE TYPE BY FILTER */
export const RETRIEVE_TYPE_BY_FILTER_REQUEST = "RETRIEVE_TYPE_BY_FILTER_REQUEST";
export const RETRIEVE_TYPE_BY_FILTER_SUCCESS = "RETRIEVE_TYPE_BY_FILTER_SUCCESS";
export const RETRIEVE_TYPE_BY_FILTER_FAIL = "RETRIEVE_TYPE_BY_FILTER_FAIL";

/**RETRIEVE TYPE BY FILTER */
export const RETRIEVE_THEME_BY_FILTER_REQUEST = "RETRIEVE_THEME_BY_FILTER_REQUEST";
export const RETRIEVE_THEME_BY_FILTER_SUCCESS = "RETRIEVE_THEME_BY_FILTER_SUCCESS";
export const RETRIEVE_THEME_BY_FILTER_FAIL = "RETRIEVE_THEME_BY_FILTER_FAIL";

/**RETRIEVE RULE BY FILTER */
export const RETRIEVE_RULE_BY_FILTER_REQUEST = "RETRIEVE_RULE_BY_FILTER_REQUEST";
export const RETRIEVE_RULE_BY_FILTER_SUCCESS = "RETRIEVE_RULE_BY_FILTER_SUCCESS";
export const RETRIEVE_RULE_BY_FILTER_FAIL = "RETRIEVE_RULE_BY_FILTER_FAIL";



/**RETRIEVE ARTICLE BY FILTER */
export const RETRIEVE_ARTICLE_BY_TYPE_REQUEST = "RETRIEVE_ARTICLE_BY_TYPE_REQUEST";
export const RETRIEVE_ARTICLE_BY_TYPE_SUCCESS = "RETRIEVE_ARTICLE_BY_TYPE_SUCCESS";
export const RETRIEVE_ARTICLE_BY_TYPE_FAIL = "RETRIEVE_ARTICLE_BY_TYPE_FAIL";



/**RETRIEVE RULES */
export const RETRIEVE_RULES_REQUEST = "RETRIEVE_RULES_REQUEST";
export const RETRIEVE_RULES_SUCCESS = "RETRIEVE_RULES_SUCCESS";
export const RETRIEVE_RULES_FAIL = "RETRIEVE_RULES_FAIL";


/**ADD NEW ARTICLE */
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAIL = "ADD_ARTICLE_FAIL";

/**DELETE ARTICLE */
export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

/**UPSATE ARTICLE */
export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";


/**ADD NEW FILE */
export const ADD_FILE_REQUEST = "ADD_FILE_REQUEST";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";
export const ADD_FILE_FAIL = "ADD_FILE_FAIL";


export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAILT";


/**ADD NEW FEEDBACK */
export const ADD_FEEDBACK_REQUEST = "ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS = "ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_FAIL = "ADD_FEEDBACK_FAIL";


/**ADD NEW FEEDBACK */
export const RETRIEVE_FEEDBACK_REQUEST = "RETRIEVE_FEEDBACK_REQUEST";
export const RETRIEVE_FEEDBACK_SUCCESS = "RETRIEVE_FEEDBACK_SUCCESS";
export const RETRIEVE_FEEDBACK_FAIL = "RETRIEVE_FEEDBACK_FAIL";

